import numpy as np
import os
import matplotlib.pyplot as plt
from src.multical.inference import run_inference
from src.multical.preprocessing.pipeline import apply_pretreatment

# =============================================================================
#                                 CONFIGURATION
# =============================================================================

# --- 1. Selection File ---
# Path to the file containing selected wavelengths (generated by run_variable_selection.py)
SELECTION_FILE = "results_var_selection/selected_wavelengths.txt"
RESULTS_DIR = "results_inference_var_sel"

# --- 2. Data Files ---
CALIBRATION_FILES = [
    ('data/exp4_refe.txt', 'data/exp4_nonda.txt'),
    #('data/exp5_refe.txt', 'data/exp5_nonda.txt'),
    ('data/exp6_refe.txt', 'data/exp6_nonda.txt'),
    ('data/exp7_refe.txt', 'data/exp7_nonda.txt'),
]

INFERENCE_FILES = [
    #('data/exp4_refe.txt', 'data/exp_04_inf.txt'),
    ('data/exp5_refe.txt', 'data/exp_05_inf.txt'),
    #('data/exp6_refe.txt', 'data/exp_06_inf.txt'),
    #('data/exp7_refe.txt', 'data/exp_07_inf.txt'),
]

# --- 3. Model Parameters ---
MODEL_TYPE = 1          # 1=PLS (recommended for selected variables)
K_VARS_PER_ANALYTE = [6, 6, 6] 
ANALYTES = ['cb', 'gl', 'xy']
COLORS = ['green', 'red', 'purple']
UNITS = 'g/L'

# --- 4. Pretreatment Pipeline ---
# MUST match run_variable_selection.py exactly!
PRETREATMENT = [
    ['Cut', 4400, 7500, 1],
    ['SG', 7, 1, 2, 1, 1],
]

# =============================================================================
#                              MAIN EXECUTION
# =============================================================================

def load_calibration_data(files):
    x_list, absor_list, wavelengths = [], [], None
    print("Loading calibration data...")
    for x_f, abs_f in files:
        if not (os.path.exists(x_f) and os.path.exists(abs_f)): continue
        try:
            xi = np.loadtxt(x_f)
            if xi.ndim == 2 and xi.shape[1] > 1: xi = xi[:, 1:]
            if xi.ndim == 1: xi = xi.reshape(-1, 1)

            with open(abs_f, 'r') as f: header = f.readline().strip().split()
            wl_curr = np.array([float(x) for x in header[1:]])
            absi = np.loadtxt(abs_f, skiprows=1)[:, 1:]

            if wavelengths is None: wavelengths = wl_curr
            x_list.append(xi)
            absor_list.append(absi)
        except Exception as e:
            print(f"Error loading {x_f}: {e}")
            
    if not x_list: return None, None, None
    x0 = np.vstack(x_list)
    absor_data = np.vstack(absor_list)
    return x0, absor_data, wavelengths

def load_inference_data(files, nc):
    x_list, absor_list, sizes, wavelengths = [], [], [], None
    print("Loading inference data...")
    for x_f, abs_f in files:
        if not os.path.exists(abs_f): continue
        try:
            with open(abs_f, 'r') as f: header = f.readline().strip().split()
            # Try parsing header starting from index 1
            wl = np.array([float(x) for x in header[1:]])
            
            absi = np.loadtxt(abs_f, skiprows=1)[:, 1:]
            if wavelengths is None: wavelengths = wl
            
            n_samples = absi.shape[0]
            sizes.append(n_samples)
            absor_list.append(absi)
            
            xi_aligned = np.full((n_samples, nc), np.nan)
            if os.path.exists(x_f):
                try:
                    ref_data = np.loadtxt(x_f)
                    if ref_data.ndim > 1 and ref_data.shape[1] >= nc + 1:
                        limit = min(n_samples, ref_data.shape[0])
                        xi_aligned[:limit, :] = ref_data[:limit, 1:nc+1]
                except: pass
            
            x_list.append(xi_aligned)

        except Exception as e:
            print(f"Error loading {abs_f}: {e}")

    if not x_list: return None, None, None, []
    
    xinf0 = np.vstack(x_list)
    absorinf_data = np.vstack(absor_list)
    return xinf0, absorinf_data, wavelengths

def filter_selected_variables(absor_pre, wl_pre, selected_wls):
    """
    Finds the indices of wl_pre that match selected_wls (within tolerance).
    Returns filtered absorbance matrix and matching wavelengths.
    """
    mask = np.zeros(len(wl_pre), dtype=bool)
    
    # Simple nearest neighbor matching or tolerance check
    # Assuming selected_wls is a subset of wl_pre
    
    found_count = 0
    for sel_wl in selected_wls:
        # Find index in wl_pre closest to sel_wl
        diffs = np.abs(wl_pre - sel_wl)
        idx = np.argmin(diffs)
        
        if diffs[idx] < 1e-1: # Tolerance 0.1 cm-1
            mask[idx] = True
            found_count += 1
            
    if found_count != len(selected_wls):
        print(f"Warning: Only matched {found_count}/{len(selected_wls)} selected wavelengths.")
        
    return absor_pre[:, mask], wl_pre[mask]

def main():
    os.makedirs(RESULTS_DIR, exist_ok=True)
    plt.rcParams['figure.max_open_warning'] = 100

    # 1. Load Selection File
    if not os.path.exists(SELECTION_FILE):
        print(f"Error: Selection file not found: {SELECTION_FILE}")
        print("Please run 'run_variable_selection.py' first.")
        return
        
    print(f"Loading selected variables from: {SELECTION_FILE}")
    selected_wls = np.loadtxt(SELECTION_FILE)
    if selected_wls.ndim == 0: selected_wls = np.array([selected_wls]) # Handle single var case
    print(f"Loaded {len(selected_wls)} selected wavelengths.")

    # 2. Load Raw Data
    x0, absor_cal_raw, wl_cal = load_calibration_data(CALIBRATION_FILES)
    if x0 is None: return

    xinf0, absor_inf_raw, wl_inf = load_inference_data(INFERENCE_FILES, len(ANALYTES))
    if absor_inf_raw is None: return

    # 3. Apply Pretreatment
    # Important: Apply pretreatment to get the full spectral processing first
    print("\nApplying Pretreatment...")
    absor_cal_pre, wl_cal_pre = apply_pretreatment(PRETREATMENT, absor_cal_raw, wl_cal, plot=False)
    absor_inf_pre, wl_inf_pre = apply_pretreatment(PRETREATMENT, absor_inf_raw, wl_inf, plot=False)

    # 4. Filter Variables
    print(f"\nFiltering for {len(selected_wls)} selected variables...")
    absor_cal_sel, wl_cal_sel = filter_selected_variables(absor_cal_pre, wl_cal_pre, selected_wls)
    absor_inf_sel, wl_inf_sel = filter_selected_variables(absor_inf_pre, wl_inf_pre, selected_wls)
    
    print(f"Calibration data shape: {absor_cal_sel.shape}")
    print(f"Inference data shape:   {absor_inf_sel.shape}")

    # 5. Run Inference Engine
    # Construct input matrices for engine (Row 0 is wavelength)
    absor0 = np.vstack([wl_cal_sel, absor_cal_sel])
    absorinf0 = np.vstack([wl_inf_sel, absor_inf_sel])
    
    print("\nRunning Inference with Selected Variables...")
    
    # We pass empty pretreatment list [] because data is already pretreated & filtered
    X_pred, rmsecv = run_inference(
        MODEL_TYPE, 2, 0, K_VARS_PER_ANALYTE, len(ANALYTES), ANALYTES, UNITS, 
        x0, absor0, xinf0, absorinf0, 
        pretreat_list=[], pretreatinf_list=[],  # ALREADY PRETREATED
        analysis_list=[], analysisinf_list=[], 
        leverage=0, output_dir=RESULTS_DIR, colors=COLORS
    )
    
    if X_pred is not None:
        print(f"\nInference Complete. Predictions saved to: {RESULTS_DIR}")

if __name__ == "__main__":
    main()
